### ISSUE TITLE
Change from PHP 5.6 to PHP 5.5.9

### ISSUE THREAD

**Issue by tacone** [WildSideUK/Laravel-Userstamps#1]
Hello, thank you very much for putting together this package.

Our company is still stuck with PHP 5.5 in our production environments. When I found your package, I could not install it because `composer.json` dictates PHP 5.6 at minimum.

After inspecting the code I found no reason it wouldn't work on PHP 5.5. I downloaded the zip, added an entry to the autoloader and tested it throughly. It works perfectly.

Since it's so simple, I see no drawback in downgrading the requirements to PHP 5.5. Could you make the minimum requirement to be PHP 5.5.9? (same as Laravel 5.1 LTS)

**Comment by mattmcdonald-uk** [comment]
Agreed. Thanks for the PR.
