### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by tanhs** [WildSideUK/Laravel-Userstamps#10]
I tried the following it doesn't work
1.  create new - it updates all including the updated_by & created_by
2.  I tried to update the record, i use "save()" or "update()" both no effect.
Do you have any clue?

User.php
use Laratrust\Traits\LaratrustUserTrait;
use Wildside\Userstamps\Userstamps;

class User extends Authenticatable
{
    use Notifiable;
    use LaratrustUserTrait;
    use Userstamps;

    protected $fillable = [
        'name', 'email', 'password', 'created_at', 'updated_at', 'created_by', 'updated_by'
    ];
...

**Comment by mattmcdonald-uk** [comment]
Did you have an active user when you tested saving and updating a model? If there's no user to be found the `created_by` and `updated_by` fields will remain null.

Other than that, difficult to assist here without a specific bug.

**Comment by luchorengo** [comment]
Same issue here. `updated_by` column is not set when using `update()` method

```
$updated_customer['name'] = 'John Doe';
$customer = Customer::findOrFail($request->id);
$customer->update($updated_customer);
```
