### ISSUE TITLE
Column not found: 1054 Unknown column 'updated_by' in 'field list' ...

### ISSUE THREAD

**Issue by badrshs** [WildSideUK/Laravel-Userstamps#15]
is it possible to work only on created_by (without updated_by)? 
I'm working on project which does not support any update and it's not necessary for me to insert updated_by to my database without reason 

any help please ?

**Comment by mattmcdonald-uk** [comment]
If you update to the 0.5.1 you will be able to set the `UPDATED_BY` constant to `null` to disable it, similar to the behaviour of the `UPDATED_AT` constant used by Laravel.

e.g. `const UPDATED_BY = null`

**Comment by badrshs** [comment]
thank you so much for your help , I updated now and the problem is solved 👍
