### ISSUE TITLE
auth guard getprovider returns null

### ISSUE THREAD

**Issue by rubanshah** [WildSideUK/Laravel-Userstamps#17]
i am getting following error

Call to a member function getModel() on null
Symfony\Component\Debug\Exception\FatalThrowableError
...\vendor\wildside\userstamps\src\Userstamps.php

and error is thrown from 

```

protected function getUserClass()
    {
        if (get_class(auth()) === 'Illuminate\Auth\Guard') {
            return auth() -> getProvider() -> getModel();
        }
        return auth() -> guard() -> getProvider() -> getModel();
    }

```

but when i replace eht auth()->gurad()
to 
auth()->guard('web') it works

```
protected function getUserClass()
    {
        if (get_class(auth()) === 'Illuminate\Auth\Guard') {
            return auth() -> getProvider() -> getModel();
        }
        return auth() -> guard('web') -> getProvider() -> getModel();
    }

```
i am using laravel 5.5 and passport api authentication

**Comment by mattmcdonald-uk** [comment]
I can't reproduce this on a clean Laravel 5.5 install using Passport.

If you can provide a simplified reproducible example repository I'll re-open this and take a look.
