### ISSUE TITLE
Hard coded created_by implemented instead of getCreatedByColumn

### ISSUE THREAD

**Issue by tayfunkayahan** [WildSideUK/Laravel-Userstamps#20]
Hi @mattmcdonald-uk,

Recently just began to use your package and saw something weird.. You allow the developers to change the `created_by`, `updated_by` etc columns by defining constants, but the `belongsTo` functionality is using a hard coded column name.

<img width="789" alt="schermafbeelding 2018-07-18 om 17 18 07" src="https://user-images.githubusercontent.com/10990971/42891024-9d6ea774-8aae-11e8-8f17-2d2c2ddd9e4e.png">

I've changed it on my localhost to use the following:
<img width="803" alt="schermafbeelding 2018-07-18 om 17 19 08" src="https://user-images.githubusercontent.com/10990971/42891062-b51942da-8aae-11e8-9222-d01a52a96f4c.png">

I guess it's something which went wrong, if yes than I'll make a PR right away to fix this problem.

Like to hear!

Cheers

**Comment by mattmcdonald-uk** [comment]
Good catch, yes a PR would be great.

**Comment by tayfunkayahan** [comment]
@mattmcdonald-uk thnx for the quick response, will make it in 10.

**Comment by tayfunkayahan** [comment]
@mattmcdonald-uk https://github.com/WildSideUK/Laravel-Userstamps/pull/21

**Comment by mattmcdonald-uk** [comment]
Perfect thanks.
