### ISSUE TITLE
userstamps() in migrations

### ISSUE THREAD

**Issue by eleftrik** [WildSideUK/Laravel-Userstamps#28]
Adding a `userstamps()` method to be used in migrations could be useful.
For example:

```
...
$table->timestamps();
$table->userstamps();
$table->softDeletes();

```

Thank you!

**Comment by willpower232** [comment]
Have a look at https://github.com/WildSideUK/Laravel-Userstamps/issues/4#issuecomment-468251999

**Comment by mattmcdonald-uk** [comment]
This might be introduced in the future, but earlier Laravel 5.x versions don't support Blueprint Macros.
