### ISSUE TITLE
Laravel 5.3.24

### ISSUE THREAD

**Issue by arnoldjp57** [WildSideUK/Laravel-Userstamps#3]
When I try and delete a record I get error ....
 
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_by' in 'field list'  ..... 
 
My Model does not have softdeletes enabled

I ran the migration to create the created_by and updated_by fields .....

**Comment by mattmcdonald-uk** [comment]
Can you try using just released version 0.1.3 and see if this is still an issue.

**Comment by arnoldjp57** [comment]
Fixed .... Thanks a stack, or as we say is South Africa  ...   LEKKER 👍
