### ISSUE TITLE
Two queries executed when deleting

### ISSUE THREAD

**Issue by Nagasir** [WildsideUK/Laravel-Userstamps#33]
<img width="773" alt="Screen Shot 2019-10-15 at 22 24 48" src="https://user-images.githubusercontent.com/7009093/66846347-e73cc680-ef9b-11e9-8e05-9a67ec6e6e84.png">

`$detail = UserDetails::find($request->id);`
`$detail->delete()`

Im using laravel telescope for debugging, and I found that two queries are executed when deleting a record (SoftDeleted). 

Laravel 5.8 with Homestead.
Package version 0.6.0

**Comment by mattmcdonald-uk** [comment]
Unfortunately this is a limitation with how the soft delete query works in Laravel. 

Only the `deleted_at` and `updated_at` columns are included in the update query, so a separate query needs to be executed to set the `deleted_by` column.
