### ISSUE TITLE
suggestion, add user name

### ISSUE THREAD

**Issue by DanielKimmich** [WildsideUK/Laravel-Userstamps#35]
It is an excellent package to use in our projects. Thank you very much for your help.

I have the following suggestion, which makes it more practical to use the name of the user that I create, update or delete:

Add the following to the model:

protected $ appends = ['created_by_user', 'updated_by_user', 'deleted_by_user'];

Public function getCreatedByUserAttribute ()
    {
        if (! empty ($ this-> creator-> name)) {
            return $ this-> creator-> name;
        } else {
            return '';
        }
    }

    Public function getUpdatedByUserAttribute ()
    {
        if (! empty ($ this-> editor-> name)) {
            return $ this-> editor-> name;
        } else {
            return '';
        }
    }

    Public function getDeletedByUserAttribute ()
    {
        if (! empty ($ this-> destroyer-> name)) {
            return $ this-> destroyer-> name;
        } else {
            return '';
        }
    }

You could declare in the model which username to return
const USER_BY = 'name'; // const USER_BY = 'email';

Regards,

**Comment by mattmcdonald-uk** [comment]
I would suggest creating your own trait to handle this.

**Comment by DanielKimmich** [comment]
OK, Thank you
