### ISSUE TITLE
detach doesn't work with userstamps

### ISSUE THREAD

**Issue by canatufkansu** [WildsideUK/Laravel-Userstamps#39]
When there is an belongstomany relationship, detach/attach methods doesn't fill user stamps fields.

For example;

```
Auth::user()->buyerDemandActions()->detach($args['buyer_demand_id']);
```

Doesn't fill deleted_by in the pivot table.

**Comment by mattmcdonald-uk** [comment]
Laravel pivot models don't support soft deletes.
