### ISSUE TITLE
Question about avoiding load three time relation with user model

### ISSUE THREAD

**Issue by Wit3** [WildsideUK/Laravel-Userstamps#47]
Hi, if i would to load editor, creator and destroyer relationship without n+1 queries, how can implementing it?
Beacause if i load the three entities relationship

```
->with(['creator','editor','destroyer'])
```
This execute three query on user model.

How can i load in one single with?

**Comment by willpower232** [comment]
That is how Laravel works https://laravel.com/docs/9.x/eloquent-relationships#eager-loading

Hydrating related models without doing separate queries is difficult to achieve without significant drawbacks.

If you're doing something like `Posts::with(['creator','editor','destroyer'])->get()` you'll notice there are only the 3 queries on the user model using `where id in (...)`

**Comment by mattmcdonald-uk** [comment]
The same model would only be retrieved when `creator`, `editor` and `destroyer` are all the same user. But as they can be different they are unique relations and will always have separate queries.

**Comment by Wit3** [comment]
Thanks for clarifing
