### ISSUE TITLE
User model with reset password

### ISSUE THREAD

**Issue by howdu** [WildsideUK/Laravel-Userstamps#49]
Is there a way to `stopUserstamping` for the auth-backend reset password? Other than overwriting this class :(

https://github.com/laravel/ui/blob/3.x/auth-backend/ResetsPasswords.php#L107

**Comment by willpower232** [comment]
Technically if the user is updating their password then you'd want to know that the last person who updated the user was themselves?

If you're needing a more detailed history then you should use some kind of auditing of which there are many.
