### ISSUE TITLE
updated_by required

### ISSUE THREAD

**Issue by arnoldjp57** [WildSideUK/Laravel-Userstamps#5]
When I try create/update a record from a scheduled task, the auth id is not available ... Can you please add something like ...   Auth()->id ? Auth()->id : env('WS_BGTASK') instead of   Auth()->id ..... Then a user can be created for scheduled tasks and its ID updated to the .env variable ... This way I will have update/create by fields accurate

**Comment by arnoldjp57** [comment]
Maybe something like  ... creating a user and then setting up a variable in .env with that id ... then in your code Auth()->id  ..... 
Auth()->id ? Auth()->id : env('WS_BGTASK')

**Comment by mattmcdonald-uk** [comment]
I don't think this is something that belongs in this package.

If you want to set `created_by` and `updated_by` to something other than the currently authenticated user's id (which would be null if no authenticated user) then you'd need to do so manually.

So long as you flush event listeners first to prevent the trait overwriting your values, you could set the columns to whatever you wanted as part of your scheduled task.

**Comment by mattmcdonald-uk** [comment]
That said, you may have other event listeners you don't want to flush.

I've added the methods `stopUserstamping` and `startUserstamping`.

So for your scheduled task simply call `stopUserstamping` and then set `created_by` and `updated_by` manually.

**Comment by arnoldjp57** [comment]
Hi

Great ... thanks for providing a better solution than my 'cranky' idea

Regards
Arnold 

Sent from my iPhone

On 12 Jan 2017, at 20:49, Matt McDonald <notifications@github.com> wrote:

That said, you may have other event listeners you don't want to flush.

I've added the methods stopUserstamping and startUserstamping.

So for your scheduled task simply call stopUserstamping and then set created_by and updated_by manually.
