### ISSUE TITLE
Support for Laravel 11

### ISSUE THREAD

**Issue by JGlueck-WIKA** [WildsideUK/Laravel-Userstamps#52]
It would be awesome if composer.json could be updated to support Laravel 11 that got released yesterday. 🙂
At the moment, the package prevents updating to 11.

**Comment by mattmcdonald-uk** [comment]
Done in https://github.com/WildsideUK/Laravel-Userstamps/commit/4ebae014be56461acb7c2e4b6d2f86a2190307b9

**Comment by alexmayo** [comment]
> Done in [4ebae01](https://github.com/WildsideUK/Laravel-Userstamps/commit/4ebae014be56461acb7c2e4b6d2f86a2190307b9)

Amazing! Thanks for the speedy turnaround!

**Comment by JGlueck-WIKA** [comment]
Wow, that was quick; thanks a lot! 👍🏻
