### ISSUE TITLE
deleted_by not setted

### ISSUE THREAD

**Issue by nanoarmando** [WildSideUK/Laravel-Userstamps#7]
Hi!, great package here.. Congrats..

I found a little issue.. when you delete a collections of items, the deleted_by field wont be set.

Example: 

//This case fails
$users = User::all();
$users->delete();

**Comment by mattmcdonald-uk** [comment]
This should be fixed in https://github.com/WildSideUK/Laravel-Userstamps/releases/tag/0.2.3
