### ISSUE TITLE
SoftDeletes not work if SoftDeletes is used in a parent class

### ISSUE THREAD

**Issue by superbull** [WildSideUK/Laravel-Userstamps#8]
For example:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Watson\Validating\ValidatingModel;

class Base extends ValidatingModel
{
    use SoftDeletes;
}
```

```php
<?php

namespace App\Models;

use Wildside\Userstamps\Userstamps;
use App\Models\User;

class Team extends Base
{
    use Userstamps;
}
```

If you delete `Team`, the `deleted_by` field will not be filled with current user.

This is because the return value of the PHP function `class_uses` **does not include any traits used by a parent class**. See: http://php.net/manual/en/function.class-uses.php

**Comment by mattmcdonald-uk** [comment]
Thanks for opening this issue and the PR (sorry it's taken me so long to get around to looking at it!)

Agreed this is needed, but there's an existing helper method 'class_uses_recursive' which we can use to achieve this.

Fixing with 2d8e5ca872249c0a256c262f45f03e307501fdbf
